config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'dashboards#show'
  get 'dashboard' => 'dashboards#show'

  # Exceptions
  %w( 404 422 500 ).each do |code|
    match code, to: 'errors#show', code: code, via: :all
  end

  # Resources
  resource :vagrant_config, only: [:edit, :update] do
    member do
      post :reset_defaults
    end
  end

  resources :benchmark_definitions do
    resources :benchmark_executions, only: [:index, :new, :create], context: :benchmark_definition
    resources :metric_definitions, only: [:new, :create], context: :benchmark_definition
    resources :benchmark_schedules, only: [:new, :create ]
    post :clone, on: :member
  end
  resources :benchmark_schedules, only: [:index, :edit, :update ] do
    member do
      patch :activate
      patch :deactivate
    end
  end
  resources :benchmark_executions, only: [:show, :index, :destroy] do
    member do
      get :prepare_log
      get :release_resources_log
      patch :toggle_keep_alive
      post :reprovision
      post :restart_benchmark
      post :abort
    end
  end
  resources :metric_definitions, only: [:show, :edit, :destroy, :update]

  resources :metric_observations, only: [:create, :index] do
    collection { post :import }
  end
  resources :nominal_metric_observations, only: [:destroy]
  resources :ordered_metric_observations, only: [:destroy]

  resources :virtual_machine_instances do
    # Used from benchmark helper client on VMs
    collection do
      post :complete_benchmark
      post :complete_postprocessing
    end
  end

  # Redirect to 404 for any non-matching path
  match '*path', to: 'errors#show', code: 404, via: :all
end

app/models/benchmark_execution.rb
# frozen_string_literal: true

class BenchmarkExecution < ApplicationRecord
  DEFAULT_PROVIDER = Rails.application.config.supported_providers.first
  PRIORITY_HIGH = 1
  belongs_to :benchmark_definition
  validates :benchmark_definition, presence: true
  has_many :virtual_machine_instances, dependent: :destroy
  has_many :events, as: :traceable, dependent: :destroy do
    include EventsAsTraceableExtension
  end
  include EventStatusHelper
  default_scope { order('created_at DESC') }
  scope :by_status, lambda { |status|
     case status
     when 'FAILED'
       select { |e| e.failed? }
     else
       select { |e| e.status == status }
     end
   }

  def self.actives
    select { |execution| execution.active? }
  end

  after_initialize do |new_execution|
    @file_system ||= VagrantFileSystem.new(new_execution.benchmark_definition, new_execution)
    @driver ||= VagrantDriver.new(@file_system.vagrantfile_path, @file_system.log_dir)
    @benchmark_runner ||= VagrantRunner.new(@file_system.vagrant_dir)
  end

  def prepare
    @file_system.prepare_vagrantfile_for_driver
    prepare_with(@driver)
    detect_and_create_vm_instances_with(@driver)

    # Schedule StartBenchmarkExecutionJobs with higher priority than PrepareBenchmarkExecutionJobs.
    # Also consider using multiple queues since long running prepare tasks should not block short running start commands.
    # Usually the start execution job can be executed immediately here!
    Delayed::Job.enqueue(StartBenchmarkExecutionJob.new(id), priority: PRIORITY_HIGH)
  rescue => e
    puts e.message
    shutdown_after_failure_timeout
    detect_and_create_vm_instances_with(@driver) rescue nil
  end

  def shutdown_after_failure_timeout
    shutdown_after(Rails.application.config.failure_timeout)
  end

  def shutdown_after(timeout)
    Delayed::Job.enqueue(ReleaseResourcesJob.new(id), priority: PRIORITY_HIGH, run_at: timeout.from_now)
  end

  def detect_and_create_vm_instances_with(driver)
    vm_instances = driver.detect_vm_instances
    vm_instances.each do |vm|
      # HACK: Quick fix to experimentally support the softlayer provider
      # Problem: CWB currently assumes that there is a way to detect the
      # (Vagrant provider) id from within a VM
      # Workaround: This quick fix uses a self-created id to identify the instance.
      # Implication: Multi-VM benchmarks will show up the same instance id for each VM
      # Future improvement: Must think about a generic VM identification solution in future as
      # one cannot expect that the id used by the Vagrant provider (e.g., instance id for aws)
      # is available within the VM itself (e.g., via metadata query API).
      if vm[:provider_name] == 'softlayer'
        vm[:provider_instance_id] = "cwb-#{self.id}"
      end
      self.virtual_machine_instances.create(provider_name: vm[:provider_name],
                                            provider_instance_id: vm[:provider_instance_id],
                                            role: vm[:role])
    end
  end

  def prepare_with(driver)
    events.create_with_name!(:started_preparing)
    provider = self.benchmark_definition.provider_name || DEFAULT_PROVIDER
    success = driver.up(provider)
    if success
      events.create_with_name!(:finished_preparing)
    else
      event = events.create_with_name!(:failed_on_preparing)
      fail event.name
    end
  end

  def prepare_log
    @driver.up_log
  end

  def reprovision
    vagrantfile = @file_system.evaluate_vagrantfile
    @file_system.create_vagrantfile(vagrantfile)
    reprovision_with(@driver)
  rescue => e
    shutdown_after_failure_timeout
  end

  def reprovision_with(driver)
    events.create_with_name!(:started_reprovisioning)
    success = driver.reprovision
    if success
      events.create_with_name!(:finished_reprovisioning)
    else
      event = events.create_with_name!(:failed_on_reprovisioning)
      fail event.name
    end
  end

  def start_benchmark
    start_benchmark_with(@benchmark_runner)
    timeout_hours = benchmark_definition.running_timeout || Rails.application.config.default_running_timeout
    shutdown_after(timeout_hours.hours)
  rescue => e
    shutdown_after_failure_timeout
  end

  def start_benchmark_with(benchmark_runner)
    success = benchmark_runner.start_benchmark
    if success
      events.create_with_name!(:started_running)
    else
      event = events.create_with_name!(:failed_on_start_running)
      fail event.name
    end
  end

  def start_postprocessing
    start_postprocessing_with(@benchmark_runner)
  rescue => e
    shutdown_after_failure_timeout
  end

  def start_postprocessing_with(benchmark_runner)
    success = benchmark_runner.start_postprocessing
    if success
      events.create_with_name!(:started_postprocessing)
    else
      event = events.create_with_name!(:failed_on_start_postprocessing)
      fail event.name
    end
  end

  def release_resources
    check_and_log_running_timeout
    if active? && !keep_alive?
      release_resources_with(@driver)
      update_consecutive_failure_count(benchmark_definition.benchmark_schedule)
    end
  rescue => e
    shutdown_after_failure_timeout
  ensure
    schedule = benchmark_definition.benchmark_schedule
    if schedule.present? && failed? && failed_threshold_reached?(schedule)
      schedule.deactivate!
    end
  end

  # This is a heurestic to detect whether the `release_resources` was triggered
  # by an elapsed running time. It avoids duplicating failed on running events.
  # The release resources job would need to store metadata about the reason to
  # release resources (e.g., running timeout) in order to clearly identify this.
  def check_and_log_running_timeout
    if benchmark_active? && !events.last.failed?
      events.create_with_name!(:failed_on_running, 'Running timeout elapsed.')
    end
  end

  def release_resources_with(driver)
    events.create_with_name!(:started_releasing_resources)
    success = driver.destroy
    if success
      events.create_with_name!(:finished_releasing_resources)
    else
      event = events.create_with_name!(:failed_on_releasing_resources)
      fail event.name
    end
  end

  def release_resources_log
    @driver.destroy_log
  end

  def update_consecutive_failure_count(schedule)
    if schedule.present?
      failed? ? schedule.consecutive_failure_count += 1 : schedule.consecutive_failure_count = 0
    end
  end

  def failed_threshold_reached?(schedule)
    times = Rails.application.config.execution_failed_threshold
    # Current execution is included as the counter is updated before
    schedule.consecutive_failure_count > times
  end
end

app/controllers/benchmark_executions_controller.rb
# frozen_string_literal: true

class BenchmarkExecutionsController < ApplicationController
  PRIORITY_HIGH = 1
  API_METHODS = [:prepare_log, :release_resources_log]
  before_action :authenticate_user!, except: API_METHODS
  before_action :set_benchmark_definition, only: [:new, :create]
  before_action :set_benchmark_execution, except: [:index, :new, :create, ]

  def index
    if params[:context] == :benchmark_definition
      set_benchmark_definition
      @benchmark_executions = @benchmark_definition.benchmark_executions.paginate(page: params[:page])
    else
      @benchmark_executions = BenchmarkExecution
      @benchmark_executions = @benchmark_executions.by_status(params[:status]) if params[:status].present?
      @benchmark_executions = @benchmark_executions.paginate(page: params[:page])
    end
  end

  def show
    @benchmark_definition = @benchmark_execution.benchmark_definition
    @virtual_machine_instances = @benchmark_execution.virtual_machine_instances
  end

  def toggle_keep_alive
    @benchmark_execution.update_attributes!(keep_alive: params[:keep_alive].to_bool)
    flash[:success] = "Successfully #{@benchmark_execution.keep_alive? ? 'enabled' : 'disabled'} the keep alive flag."
  rescue => e
    flash[:error] = "Could not set the keep alive flage to #{params[:keep_alive]}. #{e.message}"
  ensure
    redirect_to @benchmark_execution
  end

  def reprovision
    Delayed::Job.enqueue(ReprovisionBenchmarkExecutionJob.new(@benchmark_execution.id), PRIORITY_HIGH)
    flash[:success] = 'Successfully started a reprovisioning job asynchronously.'
    redirect_to @benchmark_execution
  end

  def restart_benchmark
    Delayed::Job.enqueue(StartBenchmarkExecutionJob.new(@benchmark_execution.id), PRIORITY_HIGH)
    flash[:success] = 'Successfully started a restart benchmark job asynchronously.'
    redirect_to @benchmark_execution
  end

  def abort
    Delayed::Job.enqueue(ReleaseResourcesJob.new(@benchmark_execution.id), PRIORITY_HIGH)
    flash[:success] = 'Successfully started a release resources job asynchronously.'
    redirect_to @benchmark_execution
  end

  def prepare_log
    respond_to do |format|
      format.text { render(plain: @benchmark_execution.prepare_log) }
    end
  end

  def release_resources_log
    respond_to do |format|
      format.text { render(plain: @benchmark_execution.release_resources_log) }
    end
  end

  def new
    @benchmark_execution = @benchmark_definition.benchmark_executions.build
  end

  def create
    @benchmark_execution = @benchmark_definition.start_execution_async
    flash[:success] = "Benchmark execution for
                       #{view_context.link_to @benchmark_definition.name, @benchmark_definition, class: 'alert-link'}
                       was successfully started asynchronously.".html_safe
    redirect_to @benchmark_execution
  rescue => e
    flash[:error] = "Benchmark execution couldn't be started asynchronously.<br>
                     #{fa_icon 'times'}. Error: #{e.message}".html_safe
    redirect_back(fallback_location: benchmark_executions_path)
  end

  def destroy
    @benchmark_execution.destroy
    redirect_to benchmark_executions_path
  end

  private
    def set_benchmark_definition
      @benchmark_definition = BenchmarkDefinition.find(params[:benchmark_definition_id])
    end

    def set_benchmark_execution
      @benchmark_execution = BenchmarkExecution.find(params[:id])
    end

    def benchmark_execution_params
      params.require(:benchmark_execution).permit(:benchmark_definition_id)
    end
end

app/helpers/benchmark_executions_helper.rb
# frozen_string_literal: true

module BenchmarkExecutionsHelper
  def execution_status_label(execution)
    if execution.failed?
      type = 'danger'
    elsif execution.active?
      type = 'success'
    elsif execution.finished?
      type = 'default'
    elsif execution.inactive?
      type = 'warning'
    end
    status_link(execution.status, type, execution)
  end

  def execution_active_indicator(execution)
    fa_icon "cog #{'spin' if execution.active?}"
  end

  def toggle_keep_alive_execution_btn(execution)
    if execution.keep_alive?
      link_to "#{fa_icon("moon-o")}&nbsp;Disable keep alive".html_safe, toggle_keep_alive_benchmark_execution_path(execution, keep_alive: false),
              method: :patch, class: 'btn btn-info btn-block', data: confirm_disable_keep_alive_execution_msg
    else
      link_to "#{fa_icon("sun-o")}&nbsp;Enable keep alive".html_safe, toggle_keep_alive_benchmark_execution_path(execution, keep_alive: true),
              method: :patch, class: 'btn btn-default btn-block', data: confirm_enable_keep_alive_execution_msg
    end
  end

  def confirm_start_execution_msg(execution)
    { confirm: "This will start a benchmark execution of the <strong>#{execution.name}</strong> benchmark." }
  end

  def confirm_reprovision_msg
    { confirm: "This action will reprovision the virtual machines again.
                Notice that you have to manually start the benchmark if desired." }
  end

  def confirm_enable_keep_alive_execution_msg
    { confirm: "This action will prevent the virtual machines of this execution from being released.<br>
                <strong>IMPORTANT: Make sure you release the resources of this execution e.g. by using the abort action.
                Anyway you MUST disable the keep alive flag before you can successfully use the abort action.</strong>" }
  end

  def confirm_disable_keep_alive_execution_msg
    { confirm: "This action will activate any scheduled release resources jobs again.<br>
                <strong>IMPORTANT: Make sure you release the resources of this execution yourself (e.g. by using the abort action)
                in case there are no more release resources jobs scheduled.</strong>" }
  end

  def confirm_restart_benchmark_msg(execution)
    { confirm: 'This action will try to restart the benchmark again via SSH. It starts the start_runner script again.' }
  end

  def confirm_abort_execution_msg(execution)
    { confirm: 'This action will abort the execution by terminating all running virtual machine instances.' }
  end

  def confirm_delete_execution_msg(execution)
    { confirm: (render 'benchmark_executions/confirm_delete', benchmark_execution: execution) }
  end

  def live_log_id(event)
    if event.started_preparing?
      'prepare'
    elsif event.started_releasing_resources?
      'releaseResources'
    end
  end

  def live_log_path(event)
    if event.started_preparing?
      prepare_log_benchmark_execution_path(event.traceable, format: :txt)
    elsif event.started_releasing_resources?
      release_resources_log_benchmark_execution_path(event.traceable, format: :txt)
    end
  end

  def benchmark_duration_formatted(execution)
    if execution.benchmark_started?
      duration = execution.benchmark_duration
      duration == 0 ? '' : distance_of_time_in_words(duration).humanize
    else
      execution.failed? ? 'Not started' : 'Not started yet'
    end
  end

  def execution_duration_formatted(execution)
    if execution.started?
      duration = execution.duration
      duration == 0 ? '' : distance_of_time_in_words(duration).humanize
    else
      execution.failed? ? 'Not started' : 'Not started yet'
    end
  end

  # No usages yet: NOTE: This is a very expensive operation as the active state is calculated based on the event model
  # def total_active_executions_badge(opts = {})
  #   actives_count = BenchmarkExecution.actives.count
  #   unless opts[:conditional].present? && opts[:conditional].to_s == 'true' && actives_count <= 0
  #     link_to actives_count, benchmark_executions_path(active: true), class: "badge bg-green badge-total #{opts[:html_class]}"
  #   end
  # end
end

app/views/benchmark_executions/_action_sidebar.html.erb
<div class="transparant-well">
  <% if @benchmark_execution.active? || @benchmark_execution.failed? %>
  <%= toggle_keep_alive_execution_btn(@benchmark_execution) %>
  <%= link_to "#{fa_icon 'wrench'}&nbsp;Reprovision".html_safe, reprovision_benchmark_execution_path(@benchmark_execution),
              method: :post, class: 'btn btn-default btn-block', data: confirm_reprovision_msg %>
  <%= link_to "#{restart_icon}&nbsp;Start Benchmark again".html_safe, restart_benchmark_benchmark_execution_path, method: :post, class: 'btn btn-default btn-block',
              data: confirm_restart_benchmark_msg(@benchmark_execution) %>
  <%= link_to "#{abort_icon}&nbsp;Abort".html_safe, abort_benchmark_execution_path, method: :post, class: 'btn btn-warning btn-block',
              data: confirm_abort_execution_msg(@benchmark_execution) %>
  <br>
  <% end %>
  <%= start_execution_link(@benchmark_execution.benchmark_definition, class: 'btn btn-primary btn-block') %>
  <%= link_to "#{delete_icon}&nbsp;Delete".html_safe, @benchmark_execution, method: :delete, class: 'btn btn-danger btn-block',
              data: confirm_delete_execution_msg(@benchmark_execution) %>
</div>

app/views/benchmark_executions/_benchmark_execution.html.erb
<tr>
  <td><%= execution_active_indicator(benchmark_execution) %></td>
  <td><%= execution_status_label(benchmark_execution) %></td>
  <td>
    <%= formatted_time(benchmark_execution.start_time, :date_and_time_short) %><br>
    <%= formatted_time(benchmark_execution.benchmark_start_time, :date_and_time_short) %>
  </td>
  <td>
    <%= execution_duration_formatted(benchmark_execution) %><br>
    <%= benchmark_duration_formatted(benchmark_execution) %>
  </td>
  <td><%= link_to delete_icon, benchmark_execution, method: :delete, data: confirm_delete_execution_msg(benchmark_execution), class: 'delete' %></td>
</tr>

app/views/benchmark_executions/_confirm_delete.html.erb
<strong>This action will delete this execution and all its associated:</strong><br>
<ul>
  <li>events</li>
  <li>virtual machines</li>
  <li>observed metrics</li>
</ul>

<em>WARNING:</em> Be especially cautious when trying to delete active executions.

app/views/benchmark_executions/_dashboard.html.erb
<div class="row">
  <%= render 'dashboard_widget',
             widget_class: status_bg_color(benchmark_execution.failed?),
             header: status_first_part(benchmark_execution.status),
             paragraph: status_second_part(benchmark_execution.status),
             icon: status_icon(benchmark_execution.failed?),
             footer: 'Status' %>


  <%= render 'dashboard_widget',
             widget_class: 'bg-blue',
             header: benchmark_duration_formatted(benchmark_execution),
             paragraph: (active_status(benchmark_execution.benchmark_active?) if benchmark_execution.benchmark_started?),
             icon: ion_icon('stats-bars'),
             footer: 'Benchmark Duration' %>

  <%= render 'dashboard_widget',
             widget_class: 'bg-yellow',
             header: execution_duration_formatted(benchmark_execution),
             paragraph: (active_status(benchmark_execution.active?) if benchmark_execution.started?),
             icon: fa_icon('play-circle fa-2x'),
             footer: 'Execution Duration' %>
</div>

app/views/benchmark_executions/_dashboard_widget.html.erb
<div class="col-md-4">
  <div class="small-box <%= widget_class %>">
    <div class="inner">
      <h3><%= header %></h3>
      <p><%= paragraph.present? ? paragraph : "&nbsp;".html_safe %></p>
    </div>
    <div class="icon">
      <%= icon %>
    </div>
    <span class="small-box-footer"><%= footer %></span>
  </div>
</div>

app/views/benchmark_executions/_live_log.html.erb
<% id = live_log_id(event) %>
<div id="<%= id %>LogDiv" class="timeline-body collapse in">
  <%= text_area_tag 'log', 'Loading...', class: "live-log", id: "#{id}Log", readonly: true %>
</div>

app/views/benchmark_executions/_live_log_controls.html.erb
<div class="btn-group timeline-right">
  <%= link_to path, class: 'btn btn-default btn-sm' do %>
    <%= download_icon %>&nbsp;Download
  <% end %>
  <a class="btn btn-default btn-sm" id="<%= id %>LogRefreshStart"><%= fa_icon('refresh') %>&nbsp;Start live refresh</a>
  <a class="btn btn-success btn-sm display-none" id="<%= id %>LogRefreshStop"><%= fa_icon('refresh spin') %>&nbsp;Stop live refresh</a>
  <%= link_to expand_icon, "##{id}LogDiv", 'data-toggle' => 'collapse', class: 'btn btn-default btn-sm minimize-box' %>
</div>

app/views/benchmark_executions/_message.html.erb
<%= text_area_tag 'message', event.message, class: "event-message", readonly: true %>

app/views/benchmark_executions/_timeline.html.erb
<div class="row">
  <div class="col-md-12">
    <ul class="timeline">
      <%= render benchmark_execution.events %>
    </ul>
  </div>
</div>

app/views/benchmark_executions/_vm_instances.html.erb
<div class="well">
  <h3><%= pluralize(@virtual_machine_instances.count, 'Virtual Machine') %></h3>
  <table class="table table-condensed">
    <tbody>
    <% @virtual_machine_instances.each do |vm| %>
      <tr>
        <td><strong><%= vm.provider_name %></strong></td>
        <td><%= vm.role %></td>
        <td><%= vm.provider_instance_id %></td>
        <td><%= link_to delete_icon, vm, method: :delete, data: confirm_delete_vm_instance_msg(vm), class: 'delete' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/benchmark_executions/index.html.erb
<% if @benchmark_definition.present? %>
  <!-- Index benchmark_executions for a specific benchmark_definition -->
  <% provide(:title, "Executions of #{@benchmark_definition.name}") %>
  <% content_header("#{pluralize(@benchmark_executions.count, 'Execution')} of", link_to(@benchmark_definition.name, @benchmark_definition)) %>

  <div class="row">
    <div class="col-md-9">
      <%= will_paginate @benchmark_executions %>
      <%= render 'shared/benchmark_executions', show_benchmark_definition: false %>
      <%= will_paginate @benchmark_executions %>
    </div>
    <div class="col-md-3">
      <div class="transparant-well">
        <%= button_to [@benchmark_definition, @benchmark_definition.benchmark_executions.build],
                      method: :post, class: 'btn btn-primary btn-block btn-lg',
                      data: confirm_start_execution_msg(@benchmark_definition) do %>
          <%= start_icon %>&nbsp;Start Execution
        <% end %>
      </div>
      <%= schedule_metric_sidebar(@benchmark_definition) %>
    </div>
  </div>
<% else %>
  <!-- Index all benchmark_executions -->
  <% provide(:title, 'Benchmark Executions') %>
  <% all_executions_link = link_to pluralize(@benchmark_executions.count, 'Benchmark Execution'), benchmark_executions_path %>
  <% content_header("#{all_executions_link}") %>

  Status filter:
  <%= link_to 'ALL', benchmark_executions_path, class: 'label label-default' %>
  <%= link_to 'FAILED', benchmark_executions_path(status: 'FAILED'), class: 'label label-danger' %>
  <%= link_to 'FAILED ON RUNNING', benchmark_executions_path(status: 'FAILED ON RUNNING'), class: 'label label-danger' %>
  <%= link_to 'FAILED ON RELEASING RESOURCES', benchmark_executions_path(status: 'FAILED ON RELEASING RESOURCES'), class: 'label label-danger' %>
  <%= link_to 'PREPARING', benchmark_executions_path(status: 'PREPARING'), class: 'label label-info' %>
  <%= link_to 'RUNNING', benchmark_executions_path(status: 'RUNNING'), class: 'label label-info' %>
  <%= link_to 'FINISHED', benchmark_executions_path(status: 'FINISHED'), class: 'label label-success' %>
  <%= will_paginate @benchmark_executions %>
  <%= render 'shared/benchmark_executions', show_benchmark_definition: true %>
  <%= will_paginate @benchmark_executions %>
<% end %>

app/views/benchmark_executions/show.html.erb
<% start_time = @benchmark_execution.start_time %>
<% provide(:title, "Execution #{formatted_time(start_time, :date_only)} of #{@benchmark_definition.name}") %>
<% title = "#{execution_active_indicator(@benchmark_execution)} Execution from #{formatted_time(start_time, :date_human)}" %>
<% subtitle = "#{formatted_time(start_time, :time_only)} of #{link_to @benchmark_definition.name, @benchmark_definition}" %>
<% edit_link = link_to edit_icon, edit_benchmark_definition_path(@benchmark_definition), class: 'edit' %>
<% content_header(title, "#{subtitle} #{edit_link}") %>

<%= render 'dashboard', benchmark_execution: @benchmark_execution %>
<div class="row">
  <div class="col-md-9" id="benchmark_execution" data-id='<%= @benchmark_execution.id %>'>
    <br>
    <%= render 'timeline', benchmark_execution: @benchmark_execution %>
  </div>

  <div class="col-md-3">
    <%= render 'action_sidebar', benchmark_execution: @benchmark_execution %>
    <%= render 'vm_instances' %>
    <%= schedule_metric_sidebar(@benchmark_definition, @benchmark_execution) %>
  </div>
</div>