config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'dashboards#show'
  get 'dashboard' => 'dashboards#show'

  # Exceptions
  %w( 404 422 500 ).each do |code|
    match code, to: 'errors#show', code: code, via: :all
  end

  # Resources
  resource :vagrant_config, only: [:edit, :update] do
    member do
      post :reset_defaults
    end
  end

  resources :benchmark_definitions do
    resources :benchmark_executions, only: [:index, :new, :create], context: :benchmark_definition
    resources :metric_definitions, only: [:new, :create], context: :benchmark_definition
    resources :benchmark_schedules, only: [:new, :create ]
    post :clone, on: :member
  end
  resources :benchmark_schedules, only: [:index, :edit, :update ] do
    member do
      patch :activate
      patch :deactivate
    end
  end
  resources :benchmark_executions, only: [:show, :index, :destroy] do
    member do
      get :prepare_log
      get :release_resources_log
      patch :toggle_keep_alive
      post :reprovision
      post :restart_benchmark
      post :abort
    end
  end
  resources :metric_definitions, only: [:show, :edit, :destroy, :update]

  resources :metric_observations, only: [:create, :index] do
    collection { post :import }
  end
  resources :nominal_metric_observations, only: [:destroy]
  resources :ordered_metric_observations, only: [:destroy]

  resources :virtual_machine_instances do
    # Used from benchmark helper client on VMs
    collection do
      post :complete_benchmark
      post :complete_postprocessing
    end
  end

  # Redirect to 404 for any non-matching path
  match '*path', to: 'errors#show', code: 404, via: :all
end

app/models/benchmark_schedule.rb
# frozen_string_literal: true

require 'pathname'
require 'fileutils'
require 'erb'
class BenchmarkSchedule < ApplicationRecord
  scope :actives, -> { where(active: true) }
  DEFAULT_TEMPLATE_PATH = Rails.application.config.benchmark_schedule_template
  DEFAULT_SCHEDULE_PATH = Rails.application.config.benchmark_schedule
  belongs_to :benchmark_definition
  validates :benchmark_definition, presence: true
  # Very loose matching. Does no complete validation. Matches:
  # 1) MUST contain 4 whitespaces (separating the 5 columns which may contain arbitrary characters)
  # 2) MUST NOT start with '*' to avoid the mistake that a benchmark is run every minute!
  VALID_CRON_EXPRESSION_REGEX = /[^\*].*\s.+\s.+\s.+\s.+/
  validates :cron_expression, presence: true,
                              format: { with: VALID_CRON_EXPRESSION_REGEX,
                                        message: "Cron expression MUST NOT start with '*' and
                                                  MUST contain 4 whitespaces separating the 5 columns." }
  after_create   :update_system_crontab_if_active
  before_destroy { self.active = false; save }
  after_update :check_and_update_system_crontab_after_update

  def activate!
    self.active = true
    save!
  end

  def deactivate!
    self.active = false
    save!
  end

  # Gem that with 'best effort' translation attempt
  # The best known cron expression to english translator has been found here but this requires php installed:
  # http://www.joostbrugman.com/bitsofthought/page/4/Converting_Crontab_Entries_To_Plain_English_%28Or_Any_Other_Language%29
  def cron_expression_in_english
    Cron2English.parse(self.cron_expression).join(' ')
  rescue Cron2English::ParseException => e
    e.message
  end

  def self.update_system_crontab
    schedule = generate_schedule_from_template(DEFAULT_TEMPLATE_PATH)
    write_content_to_file(schedule, DEFAULT_SCHEDULE_PATH)
    apply_schedule_to_system_crontab(DEFAULT_SCHEDULE_PATH) unless ENV['UPDATE_SYSTEM_CRONTAB'] == 'false'
  end

  def self.generate_schedule_from_template(template_path = DEFAULT_TEMPLATE_PATH)
    template = ERB.new File.read(template_path)
    template.result(binding)
  end

  def self.apply_schedule_to_system_crontab(schedule_path = DEFAULT_SCHEDULE_PATH)
    result = %x(whenever --update-crontab -f "#{schedule_path}")
    unless $?.success?
      fail "Failed to update system crontab. #{result}"
    end
    $?.success?
  end

  def self.clear_system_crontab(schedule_path = DEFAULT_SCHEDULE_PATH)
    %x(whenever --clear-crontab -f "#{schedule_path}")
  end

  private

    def update_system_crontab_if_active
      BenchmarkSchedule.update_system_crontab if active?
    end

    def check_and_update_system_crontab_after_update
      if saved_change_to_active? || (active && saved_change_to_cron_expression?)
        BenchmarkSchedule.update_system_crontab
      end
    end

    def self.write_content_to_file(schedule, schedule_path)
      parent_dir = Pathname.new(schedule_path).parent
      FileUtils.mkdir_p(parent_dir)
      File.open(schedule_path, 'w') do |f|
        f.write(schedule)
      end
    end
end

app/controllers/benchmark_schedules_controller.rb
# frozen_string_literal: true

class BenchmarkSchedulesController < ApplicationController
  before_action :set_benchmark_schedule, only: [:edit, :update, :activate, :deactivate]
  before_action :set_benchmark_definition, only: [:new, :create]

  def new
    @benchmark_schedule = @benchmark_definition.build_benchmark_schedule
  end

  def index
    @benchmark_schedules = BenchmarkSchedule.unscoped
    @benchmark_schedules = @benchmark_schedules.actives if params[:active].present?
    @benchmark_schedules = @benchmark_schedules.paginate(page: params[:page])
  end

  def edit
    @benchmark_definition = @benchmark_schedule.benchmark_definition
  end

  def create
    @benchmark_schedule = @benchmark_definition.build_benchmark_schedule(benchmark_schedule_params)
    @benchmark_schedule.save!
    success_flash_for 'created'
    redirect_to @benchmark_definition
  rescue => error
    flash.now[:error] = error.message
    render action: 'new'
  end

  def update
    @benchmark_definition = @benchmark_schedule.benchmark_definition
    @benchmark_schedule.update!(benchmark_schedule_params)
    success_flash_for 'updated'
    redirect_to @benchmark_definition
  rescue => error
    flash.now[:error] = error.message
    render action: 'edit'
  end

  def activate
    @benchmark_definition = @benchmark_schedule.benchmark_definition
    @benchmark_schedule.activate!
    success_flash_for 'activated'
  rescue => e
    error_flash_for('activated', e.message)
  ensure
    redirect_back(fallback_location: benchmark_definitions_path)
  end

  def deactivate
    @benchmark_definition = @benchmark_schedule.benchmark_definition
    @benchmark_schedule.deactivate!
    success_flash_for 'deactivated'
  rescue => e
    error_flash_for('deactivated', e.message)
  ensure
    redirect_back(fallback_location: benchmark_definitions_path)
  end

  private
    def set_benchmark_schedule
      @benchmark_schedule = BenchmarkSchedule.find(params[:id])
    end

    def set_benchmark_definition
      @benchmark_definition = BenchmarkDefinition.find(params[:benchmark_definition_id])
    end

    def benchmark_schedule_params
      params.require(:benchmark_schedule).permit(:benchmark_definition_id, :cron_expression, :active)
    end

    def success_flash_for(action)
      flash[:success] = "Schedule for #{view_context.alert_link(@benchmark_definition)} was successfully #{action}:
                         <strong>#{@benchmark_schedule.cron_expression}</strong> <em>(#{@benchmark_schedule.cron_expression_in_english})</em>".html_safe
    end

    def error_flash_for(action, message)
      flash[:error] = "Schedule for #{view_context.alert_link(@benchmark_definition)} couldn't be #{action}. #{message}".html_safe
    end
end

app/helpers/benchmark_schedules_helper.rb
# frozen_string_literal: true

module BenchmarkSchedulesHelper
  def toggle_benchmark_schedule_link(schedule)
    toggle_benchmark_schedule(schedule, activate_class: 'activate-color', deactivate_class: 'deactivate-color')
  end

  def toggle_benchmark_schedule_btn(schedule)
    toggle_benchmark_schedule(schedule, activate_class: 'btn btn-default', deactivate_class: 'btn btn-default')
  end

  def toggle_benchmark_schedule(schedule, opts = {})
    if schedule.active?
      link_to "#{pause_icon}&nbsp;Deactivate Schedule".html_safe, deactivate_benchmark_schedule_path(schedule), method: :patch, class: opts[:deactivate_class]
    else
      link_to "#{start_icon}&nbsp;Activate Schedule".html_safe, activate_benchmark_schedule_path(schedule), method: :patch, class: opts[:activate_class]
    end
  end

  # You may pass optional html parameters such as { class: 'pull-right', title: 'I'm a tooltip }
  def benchmark_schedule_label(schedule, opts = {})
    if schedule.active?
      schedule_label(schedule, 'success', opts)
    else
      schedule_label(schedule, 'default', opts)
    end
  end

  def total_active_schedules_badge(opts = {})
    actives_count = BenchmarkSchedule.actives.count
    unless opts[:conditional].present? && opts[:conditional].to_s == 'true' && actives_count <= 0
      link_to actives_count, benchmark_schedules_path(active: true), class: "badge bg-green badge-total #{opts[:html_class]}"
    end
  end

  private

    def schedule_label(schedule, type, opts)
      base_html_class = "label label-#{type}"
      html_class = opts[:class].present? ? "#{base_html_class} #{opts[:class]}" : base_html_class
      args = opts.merge(class: html_class)
      link_to schedule.cron_expression, edit_benchmark_schedule_path(schedule), args
    end
end

app/views/benchmark_schedules/_benchmark_schedule.html.erb
<% benchmark = benchmark_schedule.benchmark_definition %>
<tr>
  <td><%= render 'benchmark_schedules/conditional_label', schedule: benchmark_schedule,
                 benchmark_definition: benchmark %></td>
  <td><%= link_to benchmark.name, benchmark %></td>
  <td><%= benchmark_schedule.cron_expression_in_english %></td>
</tr>

app/views/benchmark_schedules/_conditional_label.html.erb
<% if schedule.present? %>

  <div class="btn-group inline-flex">
    <div class="tooltip-options inline-flex">
      <%= benchmark_schedule_label(schedule, { class: 'schedule-align', title: schedule.cron_expression_in_english.html_safe }) %>
    </div>
    <button type="button" class="btn btn-default btn-xs dropdown-toggle schedule-align" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to "#{edit_icon}&nbsp;Edit".html_safe, edit_benchmark_schedule_path(schedule), class: 'edit-color' %></li>
      <li><%= toggle_benchmark_schedule_link(schedule) %></li>
    </ul>
  </div>

<% else %>

  <%= link_to new_benchmark_definition_benchmark_schedule_path(benchmark_definition), class: 'btn btn-default btn-xs' do %>
    <%= schedule_icon %>&nbsp;Create Schedule
  <% end %>

<% end %>

app/views/benchmark_schedules/_cron_expression_reference.html.erb
<table class="table table-bordered cron-reference">
  <tbody>
  <tr>
    <th>Minute</th>
    <th>Hour</th>
    <th>Day of month</th>
    <th>Month</th>
    <th>Day of week</th>
  </tr>
  <tr>
    <td>0-59</td>
    <td>0-23</td>
    <td>1-31</td>
    <td>1-12</td>
    <td>0-7</td>
  </tr>
  </tbody>
</table>

<h3>Example</h3>
<blockquote>
  <p><code class="cron-example">0 10,22 * * 1-5</code></p>
  <small>at 10 am and pm on weekdays</small>
</blockquote>

app/views/benchmark_schedules/_form.html.erb
<div class="col-md-4">
  <div class="box">
    <div class="box-body">
      <%= simple_form_for(@benchmark_schedule, url: url) do |f| %>
        <%= f.input :cron_expression %>
        <%= f.input :active %>
        <%= f.submit class: 'btn btn-primary', value: submit_action %>
      <% end %>
    </div>
  </div>
</div>

<div class="col-md-8">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Cron-Expression Reference</h3>
      <div class="box-tools pull-right">
        <%= link_to 'https://corntab.com/', target: '_blank', style: 'margin-right: 10px;' do %>
          Corntab - Online Crontab Editor&nbsp;<%= fa_icon('external-link') %>
        <% end %>
        <%= link_to 'https://linux.die.net/man/5/crontab', target: '_blank' do %>
          Man pages - crontab(5)&nbsp;<%= fa_icon('external-link') %>
        <% end %>
      </div>
    </div>
    <div class="box-body">
      <%= render 'cron_expression_reference' %>
    </div>
  </div>
</div>

app/views/benchmark_schedules/edit.html.erb
<% provide(:title, "Edit Schedule for #{@benchmark_definition.name} Benchmark") %>
<% content_header('Edit Schedule', "for #{link_to @benchmark_definition.name, @benchmark_definition } Benchmark") %>

<%= render 'form', submit_action: 'Update Schedule', url: benchmark_schedule_path(@benchmark_schedule) %>

app/views/benchmark_schedules/index.erb
TODO: List benchmark schedules here

app/views/benchmark_schedules/index.html.erb
<% provide(:title, 'Schedules') %>
<% all_schedules_link = link_to pluralize(@benchmark_schedules.count, 'Schedule'), benchmark_schedules_path %>
<% content_header("#{all_schedules_link} #{total_active_schedules_badge(html_class: 'badge-lg')}") %>

<%= will_paginate %>
<div class="box-body table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Cron-Expression</th>
        <th>Benchmark Definition</th>
        <th>Cron-Expression in English</th>
      </tr>
    </thead>
    <tbody>
      <%= render @benchmark_schedules %>
    </tbody>
  </table>
</div>
<%= will_paginate %>

app/views/benchmark_schedules/new.html.erb
<% provide(:title, "Create Schedule for #{@benchmark_definition.name} Benchmark") %>
<% content_header('Create Schedule', "for #{link_to @benchmark_definition.name, @benchmark_definition } Benchmark") %>

<%= render 'form', submit_action: 'Create Schedule', url: benchmark_definition_benchmark_schedules_path(@benchmark_definition) %>