config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'dashboards#show'
  get 'dashboard' => 'dashboards#show'

  # Exceptions
  %w( 404 422 500 ).each do |code|
    match code, to: 'errors#show', code: code, via: :all
  end

  # Resources
  resource :vagrant_config, only: [:edit, :update] do
    member do
      post :reset_defaults
    end
  end

  resources :benchmark_definitions do
    resources :benchmark_executions, only: [:index, :new, :create], context: :benchmark_definition
    resources :metric_definitions, only: [:new, :create], context: :benchmark_definition
    resources :benchmark_schedules, only: [:new, :create ]
    post :clone, on: :member
  end
  resources :benchmark_schedules, only: [:index, :edit, :update ] do
    member do
      patch :activate
      patch :deactivate
    end
  end
  resources :benchmark_executions, only: [:show, :index, :destroy] do
    member do
      get :prepare_log
      get :release_resources_log
      patch :toggle_keep_alive
      post :reprovision
      post :restart_benchmark
      post :abort
    end
  end
  resources :metric_definitions, only: [:show, :edit, :destroy, :update]

  resources :metric_observations, only: [:create, :index] do
    collection { post :import }
  end
  resources :nominal_metric_observations, only: [:destroy]
  resources :ordered_metric_observations, only: [:destroy]

  resources :virtual_machine_instances do
    # Used from benchmark helper client on VMs
    collection do
      post :complete_benchmark
      post :complete_postprocessing
    end
  end

  # Redirect to 404 for any non-matching path
  match '*path', to: 'errors#show', code: 404, via: :all
end

app/models/benchmark_definition.rb
# frozen_string_literal: true

require 'securerandom'
class BenchmarkDefinition < ApplicationRecord
  extend Enumerize
  PROVIDERS = Rails.application.config.supported_providers
  enumerize :provider_name, in: PROVIDERS, default: PROVIDERS.first
  has_one :benchmark_schedule, dependent: :destroy
  has_many :metric_definitions, dependent: :destroy
  has_many :benchmark_executions, dependent: :destroy do
    def has_active?
      actives.any?
    end

    def actives
      self.select { |execution| execution.active? }
    end

    # any? does consider built executions via self.benchmark_execution.build
    # Therefore the any valid check is required to determine whether there are existing executions.
    # Otherwise unexpected results appear on views with a start execution button.
    def any_valid?
      first_valid = self.find { |execution| execution.id.present? }
      first_valid.present?
    end
  end

  validates :running_timeout, presence: true,
                              numericality: { only_integer: true, greater_than: 0 }
  # Notice: Uniqueness constraint may be violated by occurring race conditions with database adapters
  # that do not support case-sensitive indices. This case should practically never occur is therefore not handled.
  MAX_NAME_LENGTH = 70
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { in: 3..MAX_NAME_LENGTH }
  validates :provider_name, presence: true
  # TODO: Add further validations and sanity checks for Vagrantfile after dry-up has been completed.
  validates :vagrantfile, presence: true
  before_save :ensure_name_integrity
  scope :search, ->(query) { where(['lower(name) LIKE ?', "%#{query.downcase}%"]) }
  default_scope { order('created_at DESC') }

  def virtual_machine_instances
    VirtualMachineInstance.where(benchmark_execution_id:
                                   BenchmarkExecution.select('id').where(benchmark_definition_id: self.id))
  end

  def self.max_name_length
    MAX_NAME_LENGTH
  end

  def self.start_execution_async_for_id(benchmark_definition_id)
    benchmark_definition = find(benchmark_definition_id)
    benchmark_definition.start_execution_async
  end

  # May throw an exception on create or enqueue
  def start_execution_async
    benchmark_execution = benchmark_executions.create!
    benchmark_execution.events.create_with_name!(:created)
    enqueue_prepare_job(benchmark_execution)
    benchmark_execution
  end

  # May throw an exception on enqueue
  def enqueue_prepare_job(benchmark_execution)
    begin
      prepare_job = PrepareBenchmarkExecutionJob.new(benchmark_execution.id)
      Delayed::Job.enqueue(prepare_job)
    rescue => e
      benchmark_execution.destroy
      raise e
    end
  end

  def clone
    # The block will be called for original and each included association
    benchmark_definition = self.deep_clone include: [ :metric_definitions, :benchmark_schedule ] do |original, clone|
      case clone.class.name
      when 'BenchmarkDefinition'
        # Avoid name collision if copying a benchmark multiple times
        clone.name = "#{original.name} copy (#{SecureRandom.hex(1)})"
      when 'BenchmarkSchedule'
        # Disable schedule if active
        clone.active = false if clone.present?
      end
    end
    benchmark_definition.save!
    benchmark_definition
  end

  private

    def ensure_name_integrity
      if self.name_changed? && self.benchmark_executions.any?
        errors.add(:base, 'The name of a benchmark definition cannot be changed if any benchmark executions are present.')
        throw(:abort)
      else
        true
      end
    end
end

app/controllers/benchmark_definitions_controller.rb
# frozen_string_literal: true

class BenchmarkDefinitionsController < ApplicationController
  include BenchmarkDefinitionsHelper
  before_action :set_benchmark_definition, only: [:show, :edit, :update, :destroy]
  before_action :check_and_show_executions_integrity_warning, only: [:edit, :update]

  def index
    @benchmark_definitions = BenchmarkDefinition
    @benchmark_definitions = @benchmark_definitions.search(params[:search]) if params[:search].present?
    @benchmark_definitions = @benchmark_definitions.paginate(page: params[:page])
  end

  def show
    @benchmark_executions = @benchmark_definition.benchmark_executions.paginate(page: params['execution_page'], per_page: 10)
    @virtual_machine_instances = @benchmark_definition.virtual_machine_instances.paginate(page: params[:page], per_page: 10)
  end

  def clone
    benchmark_definition_original = BenchmarkDefinition.find(params[:id])
    @benchmark_definition = benchmark_definition_original.clone
    @metric_definitions = @benchmark_definition.metric_definitions
    render action: 'edit'
  rescue => e
    link_to_original = view_context.link_to benchmark_definition_original.name, benchmark_definition_original, class: 'alert-link'
    flash[:error] = "Benchmark definition #{link_to_original} couldn't be cloned. #{e.message}".html_safe
    redirect_back(fallback_location: benchmark_definition_path(benchmark_definition_original))
  end

  def new
    @benchmark_definition = BenchmarkDefinition.new(vagrantfile: vagrantfile_example)
  end

  def edit
  end

  def create
    @benchmark_definition = BenchmarkDefinition.new(benchmark_definition_params)

    if @benchmark_definition.save
      show_success_flash 'created'
      redirect_to edit_benchmark_definition_path(@benchmark_definition)
    else
      render action: 'new'
    end
  end

  def update
    @benchmark_definition.update!(benchmark_definition_params)
    show_success_flash 'updated'
    if @benchmark_definition.benchmark_executions.any?
      redirect_to @benchmark_definition
    else
      redirect_to edit_benchmark_definition_path(@benchmark_definition)
    end
  rescue => e
    flash[:error] = e.message
    render action: 'edit'
  end

  def destroy
    @benchmark_definition.destroy!
    redirect_to benchmark_definitions_url
  rescue => e
    flash[:error] = e.message
    redirect_to @benchmark_definition
  end

  private
    def set_benchmark_definition
      @benchmark_definition = BenchmarkDefinition.find(params[:id])
    end

    def benchmark_definition_params
      params.require(:benchmark_definition).permit(:name, :running_timeout, :vagrantfile, :provider_name)
    end

    def check_and_show_executions_integrity_warning
      if @benchmark_definition.benchmark_executions.any?
        flash.now[:info] = 'You try to modify a benchmark that has already been executed.'
      end
    end

    def show_success_flash(action)
      flash[:success] = "Benchmark definition <strong>#{view_context.link_to @benchmark_definition.name, @benchmark_definition, class: 'alert-link'}</strong> was successfully #{action}.".html_safe
    end

    def vagrantfile_example
      template = ERB.new File.read(Rails.application.config.vagrantfile_example)
      template.result
    end
end

app/helpers/benchmark_definitions_helper.rb
# frozen_string_literal: true

module BenchmarkDefinitionsHelper
  def confirm_delete_benchmark_msg(benchmark_definition)
    { confirm: (render 'benchmark_definitions/confirm_delete', benchmark_definition: benchmark_definition) }
  end

  def schedule_metric_sidebar(benchmark_definition, benchmark_execution = {})
    observation_link_params = benchmark_execution.present? ? { benchmark_execution_id: benchmark_execution.id } : {}
    render 'shared/schedule_metric_sidebar', benchmark_definition: @benchmark_definition,
                                             benchmark_schedule:   @benchmark_definition.benchmark_schedule,
                                             metric_definitions:   @benchmark_definition.metric_definitions.sort_by(&:name),
                                             observation_link_params: observation_link_params
  end

  def vagrantfile_error?(benchmark_definition)
    benchmark_definition.errors[:vagrantfile].any?
  end

  def start_execution_link(benchmark_definition, opts)
    link_to "#{start_icon}&nbsp;Start Execution".html_safe, [benchmark_definition, benchmark_definition.benchmark_executions.build],
                method: :post, class: opts[:class],
                data: confirm_start_execution_msg(benchmark_definition)
  end
end

app/views/benchmark_definitions/_benchmark_definition.erb
<tr>
  <td>
    <%= link_to edit_icon, edit_benchmark_definition_path(benchmark_definition), class: 'edit' %>
    <% confirm_delete_msg = { confirm: (render 'benchmark_definitions/confirm_delete', benchmark_definition: benchmark_definition) } %>
    <%= link_to clone_icon, clone_benchmark_definition_path(benchmark_definition), method: :post, class: 'clone' %>
    <% confirm_start_msg = { confirm: 'This will start a benchmark execution.' } %>
    <%= link_to delete_icon, benchmark_definition, method: :delete, data: confirm_delete_msg, class: 'delete' %>
    <%= link_to start_icon, [benchmark_definition, benchmark_definition.benchmark_executions.build], method: :post, class: 'start', data: confirm_start_msg %>
  </td>
  <td>
    <%= link_to benchmark_definition.name, benchmark_definition, class: 'first-row' %>
  </td>
  <td>
    <%= link_to benchmark_definition_benchmark_executions_path(benchmark_definition) do %>
      <%= pluralize(benchmark_definition.benchmark_executions.count, 'Execution') %>
    <% end %>
    <% if benchmark_definition.benchmark_executions.has_active? %>
      &nbsp;<small class="badge bg-green"><%= benchmark_definition.benchmark_executions.actives.count %></small>
    <% end %>
  </td>
  <td>
    <% schedule = benchmark_definition.benchmark_schedule %>
    <% if schedule.present? %>
      <div class="btn-group inline-flex">
      <div class="tooltip-options inline-flex">
        <% if schedule.active? %>
          <span class="label label-success"><%= schedule.cron_expression %></span>
        <% else %>
          <%= link_to schedule.cron_expression, schedule, class: 'label label-default schedule-align', title: schedule.cron_expression_in_english.html_safe %>
        <% end %>
      </div>
        <button type="button" class="btn btn-default btn-xs dropdown-toggle schedule-align" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "#{edit_icon}&nbsp;Edit".html_safe, edit_benchmark_schedule_path(schedule), class: 'edit-color' %></li>
          <li><%= toggle_benchmark_schedule_btn(schedule) %></li>
        </ul>
      </div>
    <% else %>
      <%= link_to new_benchmark_definition_benchmark_schedule_path(benchmark_definition), class: 'btn btn-default btn-xs' do %>
        <%= schedule_icon %>&nbsp;Create Schedule
      <% end %>
    <% end %>
  </td>
</tr>

app/views/benchmark_definitions/_benchmark_definition.html.erb
<tr>
  <td>
    <div class="icons-lg">
      <%= link_to edit_icon, edit_benchmark_definition_path(benchmark_definition), class: 'edit' %>
      <%= link_to clone_icon, clone_benchmark_definition_path(benchmark_definition), method: :post, class: 'clone' %>
      <%= link_to delete_icon, benchmark_definition, method: :delete, data: confirm_delete_benchmark_msg(benchmark_definition), class: 'delete' %>
      <%= link_to start_icon, [benchmark_definition, benchmark_definition.benchmark_executions.build], method: :post, class: 'start', data: confirm_start_execution_msg(benchmark_definition) %>
    </div>
  </td>
  <td>
    <%= link_to benchmark_definition.name, benchmark_definition, class: 'bold' %>
  </td>
  <td>
    <%= link_to benchmark_definition_benchmark_executions_path(benchmark_definition) do %>
      <%= pluralize(benchmark_definition.benchmark_executions.count, 'Execution') %>
    <% end %>
  </td>
  <td>
    <%= render 'benchmark_schedules/conditional_label', schedule: benchmark_definition.benchmark_schedule,
                                                        benchmark_definition: benchmark_definition %>
  </td>
</tr>

app/views/benchmark_definitions/_benchmark_executions.html.erb
<%= will_paginate @benchmark_executions %>
<div id='defaultTable' class='body'>
  <table class='table responsive-table'>
    <thead>
    <tr>
      <th>Status</th>
      <th>Started</th>
      <th>Ended</th>
      <th>Duration</th>
    </tr>
    </thead>
    <tbody>
    <% @benchmark_executions.each do |benchmark_execution| %>
      <tr>
        <td>
          <%= benchmark_execution.status %>
        </td>
        <td>
          <%= benchmark_execution.start_time.present? ? benchmark_execution.start_time.to_formatted_s(:db) : '-' %>
        </td>
        <td>
          <%= benchmark_execution.end_time.present? ? benchmark_execution.end_time.to_formatted_s(:db) : '-' %>
        </td>
        <td>
          <%= benchmark_execution.start_time.present? ? distance_of_time_in_words(benchmark_execution.duration) : '-' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @benchmark_executions %>

app/views/benchmark_definitions/_benchmark_executions_box.html.erb
<div class="box collapsed-box">
  <div class="box-header">
    <h3 class="box-title">
      <%= link_to benchmark_definition_benchmark_executions_path(@benchmark_definition) do %>
        <%= pluralize(@benchmark_definition.benchmark_executions.count, 'Execution') %>
      <% end %>
    </h3>
    <%= will_paginate @benchmark_executions, class: 'pagination-box', param_name: 'execution_page' %>
    <div class="box-tools pull-right">
      <button class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse"><%= fa_icon 'minus' %></button>
    </div>
  </div>
  <div class="box-body table-responsive">
    <%= render 'shared/benchmark_executions', show_benchmark_definition: false %>
  </div>
</div>

app/views/benchmark_definitions/_confirm_delete.erb
<strong>This action will delete all associated data of <em><%= benchmark_definition.name %></em>:</strong><br>
<ul>
  <li>benchmark schedules</li>
  <li>metric definitions and its observed metrics</li>
  <li>benchmark executions and its events and virtual machines</li>
</ul>

app/views/benchmark_definitions/_confirm_delete.html.erb
<strong>This action will delete all associated data of the <em><%= benchmark_definition.name %></em> benchmark:</strong><br>
<ul>
  <li>benchmark schedules</li>
  <li>metric definitions and its observed metrics</li>
  <li>benchmark executions and its events and virtual machines</li>
</ul>

app/views/benchmark_definitions/_form.html.erb
<%= simple_form_for(@benchmark_definition) do |f| %>
  <% has_executions = @benchmark_definition.benchmark_executions.any_valid? ? { readonly: true } : {} %>

  <div class="row">
    <div class="col-xs-12 col-md-4 col-lg-4">
      <%= f.input :name, input_html: { maxlength: BenchmarkDefinition.max_name_length }.merge(has_executions) %>
    </div>
    <div class="col-xs-12 col-md-5 col-lg-5">
    <%= f.label :running_timeout, 'Timeout for running benchmark' %>
    <br>
    <br>
    <% timeout = @benchmark_definition.running_timeout || Rails.application.config.default_running_timeout %>
    <%= f.text_field :running_timeout, class: 'hour-slider',
                                       'value' => timeout,
                                       'data-slider-value' =>  timeout,
                                       'data-slider-min'   =>   '1',
                                       'data-slider-max'   => '100',
                                       'data-slider-step'  =>   '1',
                                       'data-slider-orientation'  =>   'horizontal',
                                       'data-slider-selection'  =>   'before',
                                       'data-slider-tooltip'  =>   'always',
                                       'data-slider-id'  =>   'yellow'
    %>
    </div>
    <div class="col-xs-12 col-md-3 col-lg-3">
      <%= f.input :provider_name, collection: BenchmarkDefinition.provider_name.options, include_blank: false %>
    </div>
  </div>
  <br>
  <%= render 'helper_docs' %>
  <% if vagrantfile_error?(@benchmark_definition) %>
    <%= f.label :vagrantfile, class: 'vagrantfile_error', error: true %>
  <% else %>
    <%= f.label :vagrantfile %>
  <% end %>
  <br>
  <%= f.error :vagrantfile, class: 'vagrantfile_error' %>
  <br>
  <%= f.text_area :vagrantfile %>
  <br>
  <%= f.button :submit, class: 'btn btn-primary btn-lg', value: submit_name %>
<% end %>

app/views/benchmark_definitions/_helper_docs.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= render 'shared/vagrantfile_help' %>
    </div>
    <div class="col-sm-3">
      <%= doc_link('CWB Docs + Benchmarks Collection', 'https://github.com/sealuzh/cwb-benchmarks') %>

      <ul>
        <li>
          <%= doc_link('cli-benchmark', 'https://github.com/sealuzh/cwb-benchmarks/tree/master/cli-benchmark') %><br/>
          <%= fa_icon('wrench') %>&nbsp;<%= link_to 'regexr (Regex Tool)', 'https://regexr.com/', target: '_blank' %>
        </li>
        <li>
          <%= doc_link('sysbench', 'https://github.com/sealuzh/cwb-benchmarks/tree/master/sysbench') %>
        </li>
        <li>
          <%= doc_link('iperf', 'https://github.com/sealuzh/cwb-benchmarks/tree/master/iperf') %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/benchmark_definitions/_search_bar.html.erb
<%= form_tag benchmark_definitions_path, method: 'get', class: 'input-group' do %>
  <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search by name' %>
  <div class="input-group-btn">
    <%= button_tag(type: 'submit', class: 'btn btn-primary btn-flat') do %>
      <%= search_icon %>
    <% end %>
  </div>
<% end %>

app/views/benchmark_definitions/_vagrantfile_box.html.erb
<div class="box collapsed-box">
  <div class="box-header">
    <h3 class="box-title">Vagrantfile (<%= @benchmark_definition.provider_name %>)<small><%= " Timeout: #{@benchmark_definition.running_timeout} h" if @benchmark_definition.running_timeout.present? %></small></h3>
    <div class="box-tools pull-right">
      <button id="ace_expand" class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse"><%= fa_icon 'minus' %></button>
    </div>
  </div>
  <div class="box-body" style="display: block;">
   <div id="benchmark_definition_vagrantfile"><%= @benchmark_definition.vagrantfile %></div>
  </div>
</div>

app/views/benchmark_definitions/_virtual_machine_instances_box.html.erb
<div class="box collapsed-box">
  <div class="box-header">
    <h3 class="box-title"><%= pluralize(vm_instances.count, 'Virtual Machine Instance') %></h3>
    <%= will_paginate vm_instances, class: 'pagination-box' %>
    <div class="box-tools pull-right">
      <button class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse"><%= fa_icon 'minus' %></button>
    </div>
  </div>
  <div class="box-body table-responsive">
    <%= render 'shared/virtual_machine_instances', show_benchmark_definition: false %>
  </div>
</div>

app/views/benchmark_definitions/index.html.erb
<% provide(:title, 'Benchmark Definitions') %>
<% content_header('Benchmark Definitions') %>

<div class="row">
  <div class="col-xs-12 col-md-8 col-lg-6">
    <%= render 'search_bar' %>
  </div>
  <div class="create-bm pull-right">
    <%= link_to new_benchmark_definition_path, class: 'btn btn-primary btn-lg' do %>
      <%= create_icon %>&nbsp;Create New Benchmark
    <% end %>
  </div>
</div>

<%= will_paginate class: 'col-md-8 col-md-offset-4' %>
<div class="box-body table-responsive">
  <table class="table table-hover">
    <tbody>
      <%= render @benchmark_definitions %>
    </tbody>
  </table>
</div>
<%= will_paginate class: 'col-md-8 col-md-offset-4' %>

app/views/benchmark_definitions/new.html.erb
<% provide(:title, 'Create New Benchmark') %>
<% content_header('Create New Benchmark') %>

<%= render 'form', submit_name: 'Create New Benchmark' %>

app/views/benchmark_definitions/show.html.erb
<% provide(:title, @benchmark_definition.name) %>
<% content_header('Benchmark Definition', @benchmark_definition.name) %>

<div class="row">
  <div class="col-md-9">
    <%= render 'vagrantfile_box' %>
    <%= render 'benchmark_executions_box' %>
    <%= render 'shared/virtual_machine_instances_box', show_benchmark_definition: false %>
  </div>

  <div class="col-md-3">
    <%= render 'action_sidebar' %>
    <%= schedule_metric_sidebar(@benchmark_definition) %>
  </div>
</div>